FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=off
ENV PDM_LOCATION=/opt/pdm

RUN apt-get update && apt-get install -y --no-install-recommends build-essential \
    python3-dev python3-pip libffi-dev libssl-dev libxml2-dev libxslt-dev zlib1g-dev curl && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip

RUN mkdir -p $PDM_LOCATION
RUN pip install pdm
